# Generated by Django 3.1.1 on 2020-09-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200911_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='update',
            new_name='updated',
        ),
    ]
